services:
  db:
    image: postgres:13.2
    container_name: postgres_db
    volumes:
      - ./docker/db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    expose:
      - "5432"
    ports:
      - "5454:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s
    restart: unless-stopped
    networks:
      - zalo_net

  alembic:
    image: fastapi-base:latest
    user: root  # Chạy container với user root
    environment:
      SQL_DATABASE_URL: "postgresql+psycopg2://postgres:postgres@db:5432/postgres"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        pip install --no-cache-dir -r requirements.txt &&
        alembic revision --autogenerate -m "Initial migration" &&
        alembic upgrade head
    depends_on:
      db:
        condition: service_healthy
    networks:
      - zalo_net
        
  localstack:
  # Please read this documentation first -> https://docs.localstack.cloud/user-guide/aws/s3/#s3-docker-image
  # You have to use localstack-pro to keep local data safety
  # Moreover, you need LOCALSTACK_AUTH_TOKEN to start a container:
  # Follow this documentation: https://docs.localstack.cloud/getting-started/auth-token/
  # Quick start: go to https://app.localstack.cloud/settings/auth-tokens
    container_name: zalo_localstack
    image: localstack/localstack-pro
    ports:
      - "4566:4566" # Chỉ cần mở port 4566
      # - "127.0.0.1:4566:4566"            # LocalStack Gateway
      # - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3
      - PERSISTENCE=1                    # ✅ Enable persistence
      - DASHBOARD=1
      - EDGE_PORT=4566
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-ls-MAnEDEbu-2002-dfna-qera-31239hg1f}
    volumes:
      - localstack_data:/var/lib/localstack   # ✅ Data is stored here
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/s3_bootstrap.sh:/etc/localstack/init/ready.d/s3_bootstrap.sh"
    networks:
      - zalo_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    image: fastapi-base:latest
    container_name: fastapi_app
    user: root
    environment:
      - ENVIRONMENT=local
      - SQL_DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/postgres
      - AWS_EXTERNAL_ENDPOINT_URL=${AWS_EXTERNAL_ENDPOINT_URL:-http://localhost:4566}
      - AWS_INTERNAL_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=localstack_key
      - AWS_SECRET_ACCESS_KEY=localstack_secret
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      alembic:
        condition: service_started
      localstack:
        condition: service_healthy
    networks:
      - zalo_net
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload","--reload-dir","/app"]
    volumes:
      - .:/app  # <-- This line mounts your code into the container

volumes:
  localstack_data:  # <-- Định nghĩa volume

networks:
  zalo_net:  # <-- Định nghĩa network
    driver: bridge
    name: zalo_net