version: '3.7'

services:
  db:
    image: postgres:13.2
    volumes:
      - ./docker/db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    expose:
      - 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: pg_isready -d postgres -U postgres
      interval: 5s
      timeout: 60s
      retries: 5
    restart: unless-stopped

  alembic:
    image: fastapi-base:latest
    environment:
      SQL_DATABASE_URL: 'postgresql+psycopg2://postgres:postgres@db:5432/postgres'
      SECRET_KEY: ${SECRET_KEY}
    command: [ "alembic", "upgrade", "head" ]
    depends_on:
      db: 
        condition: service_healthy

  app:
    image: fastapi-base:latest
    volumes:
      - .:/app
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      SQL_DATABASE_URL: 'postgresql+psycopg2://postgres:postgres@db:5432/postgres'
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      alembic:
        condition: service_started
      localstack:
        condition: service_healthy
    networks:
      - zalo_net
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload","--reload-dir","/app"]
    volumes:
      - .:/app  # <-- This line mounts your code into the container

volumes:
  localstack_data:  # <-- Định nghĩa volume

networks:
  zalo_net:  # <-- Định nghĩa network
    driver: bridge
    name: zalo_net